load("@npm_bazel_typescript//:index.bzl", "ts_library")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "google_visualization",
    srcs = [
        "google_visualization.ts",
    ],
    deps = [
        "@org_xprof//frontend/third_party/google_visualization",
    ],
)
