# Description
# Xprof, ML Performance Toolbox (for TPU, GPU, CPU).

package(default_visibility = [":internal"])

licenses(["notice"])

exports_files(["LICENSE"])  # Needed for internal repo.

exports_files(["tsconfig.json"])
