load("@npm_bazel_typescript//:index.bzl", "ts_library")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "angular_common_http",
    srcs = [],
    deps = [
        "@npm//@angular/common",
    ],
)

ts_library(
    name = "angular_platform-browser_animation",
    srcs = [],
    deps = [
        "@npm//@angular/platform-browser",
    ],
)

ts_library(
    name = "angular_material_expansion",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_progress_bar",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_form_field",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_icon",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_input",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_button",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_divider",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_menu",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_sidenav",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_checkbox",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_dialog",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_radio",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_progress_spinner",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_snack_bar",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_card",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_slide_toggle",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_slider",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_tooltip",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_core",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_select",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

ts_library(
    name = "angular_material_list",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)
