load("@npm_bazel_typescript//:index.bzl", "ts_library")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "constants",
    srcs = [
        "constants.ts",
        "enums.ts",
    ],
)
