/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 * All rights reserved.
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once

#include "ActivityType.h"

namespace libkineto {

class ICorrelationObserver {
 public:
  virtual ~ICorrelationObserver() {}

  // Use kind to distinguish between IDs generated by separate components.
  virtual void pushCorrelationId(ActivityType kind, uint64_t id) = 0;
  virtual void popCorrelationId(ActivityType kind) = 0;
};

} // namespace libkineto
