{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name: torch_tb_profiler
  version: "{{ data.get('version') }}"

source:
 path: "{{ environ.get('SOURCE_ROOT_DIR', '../..') }}"

requirements:
  host:
    - python
    - setuptools
    - pytorch

  run:
    - python
    - pandas
    - tensorboard

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

test:
  imports:
    - torch_tb_profiler
  source_files:
    - test
  requires:
    - tensorboard
    - pandas


about:
  home: https://github.com/pytorch/kineto/tree/main/tb_plugin
  license: BSD
  license_file: LICENSE
  summary: 'Tensoboard Plugin that provides visualization of PyTorch profiling'
